### ISSUE TITLE
Incorrect password after `login` causes a later KeyError that seems unrelated

### ISSUE THREAD

**Issue by khyox** [JBEI/edd-utils#8]
If a wrong password is entered after `session = eddu.login(edd_server=edd_server, user=user)`, then using `export_study` throws a `KeyError` exception that offers no clue to the original problem (incorrect password):

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-22-782b1326f801> in <module>
      1 df: pd.DataFrame
      2 DISKDF: str = "./fullLygosBEEPSdf_v3.pkl"
----> 3 df = eddu.export_study(session, study_slug, edd_server=edd_server)
      4 
      5 try:

~/.pyenv/versions/3.8.3/envs/KL_3.8.3/lib/python3.8/site-packages/edd_utils/__init__.py in export_study(session, slug, edd_server, verbose)
     88     # Catch the error if study slug is not found in edd_server
     89     try:
---> 90         study_id = json_response["results"][0]["pk"]
     91     except IndexError:
     92         if json_response["results"] == []:

KeyError: 'results'
```
Tested with:
  - Python 3.8.3
  - EDD-Utils version: 0.0.8

**Comment by chimaerase** [comment]
I suspect the problem is in the `login()` function.  In a recent test of mine, the test for the string 'Login failed.' on ln 59 didn't seem to work anymore.  If memory serves, `if` condition was written / tested against an older version of Django & EDD.  On quick inspection, it appears replacing it with 'not correct' would likely fix the problem.  This way of detecting login success/failure is fairly brittle, but I'm not aware of a better quick fix.

**Comment by tianar** [comment]
By looking at the login_response.text (ln 57) I found the strings corresponding to login failures (incorrect username/password, too many failed attempts). Are these strings likely to change? If not I made a quick solution reporting the login failure.
